---
- hosts: localhost
#  become: true
  connection: local

  vars_files:
    - vars/main.yml

  roles:
    - base
    - ssd
    - virtualbox
    - desktop
    - latte
    - syncthing
    - dotfiles
    - docker
    - marciopaiva.libvirt
      become: true