---
galaxy_info:
  role_name: libvirt
  author: Marcio Paiva Barbosa
  description: This role install and configure a host as a Libvirt (KVM) Hypervisor.
  company: Red Hat Consulting Brazil
  license: license (GPLv3)
  min_ansible_version: 2.4.0
  platforms:
    - name: EL
      versions:
        - 7
    - name: Fedora
      versions:
        - 29
    - name: Ubuntu
      versions:
        - bionic
    - name: Debian
      versions:
        - stretch
  galaxy_tags:
    - system
    - virtualization
    - cloud
    - kvm
    - libvirt
    - vm
  dependencies: []
