---
language: python
services: docker

env:
  global:
    - ROLE_NAME: libvirt
  matrix:
    - MOLECULE_DISTRO: centos
    - MOLECULE_DISTRO: fedora
    - MOLECULE_DISTRO: ubuntu
    - MOLECULE_DISTRO: debian

install:
  # Install test dependencies.
  - pip install molecule docker netaddr

before_script:
  # Use actual Ansible Galaxy role name for the project directory.
  - cd ../
  - mv ansible-role-$ROLE_NAME marciopaiva.$ROLE_NAME
  - cd marciopaiva.$ROLE_NAME

script:
  # Run tests.
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
