- name: Install ZSH
  pacman:
    name: 'zsh'
    state: present
  tags:
    - shell

- name: Install oh-my-zsh
  git:
    repo: https://github.com/robbyrussell/oh-my-zsh
    dest: ~/.oh-my-zsh
    update: no

- name: Install zsh-autosuggestions
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions.git
    dest: ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
    update: no

- name: Install zsh-syntax-highlighting
  git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
    update: no

- name: Install powerlevel9k theme
  git:
    repo: https://github.com/bhilburn/powerlevel9k
    dest: ~/.oh-my-zsh/custom/themes/powerlevel9k
    update: no

- name: Set ZSH as default shell
  become: yes
  become_user: root
  command: chsh -s /bin/zsh {{ ansible_user_id }}
  register: zsh_for_user
  failed_when: zsh_for_user.rc >= 1
  changed_when: zsh_for_user.rc == 0

