---
- name: stop networks if requested
  virt_net:
    name: '{{ item.name }}'
    uri: '{{ libvirt_uri }}'
    state: 'inactive'
  with_flattened: '{{ libvirt_networks }}'
  become: false
  when:
    - item.name|d()
    - item.state|d() in [ 'inactive', 'undefined', 'absent' ]

- name: undefine networks if requested
  virt_net:
    name: '{{ item.name }}'
    uri: '{{ libvirt_uri }}'
    state: 'absent'
  with_flattened: '{{ libvirt_networks }}'
  become: false
  when:
    - item.name|d()
    - item.state|d() in [ 'undefined', 'absent' ]

- name: define networks
  virt_net:
    name: '{{ item.name }}'
    uri: '{{ libvirt_uri }}'
    xml: '{{ lookup("template", "network-" + item.type + ".xml.j2") }}'
    state: 'present'
  with_flattened: '{{ libvirt_networks }}'
  become: false
  when:
    - item.name|d()
    - item.state|d("active") not in [ 'undefined', 'absent' ]
    - item.interface_present is undefined or
      item.interface_present in ansible_interfaces and not item.uri|d()

- name: start networks if not started
  virt_net:
    name: '{{ item.name }}'
    uri: '{{ libvirt_uri }}'
    state: 'active'
  with_flattened: '{{ libvirt_networks }}'
  become: false
  when:
    - item.name|d()
    - item.state is undefined or item.state in [ 'active' ]
    - item.interface_present is undefined or
      item.interface_present in ansible_interfaces and not item.uri|d()

- name: set autostart attribute on networks
  virt_net:
    name: '{{ item.name }}'
    uri: '{{ libvirt_uri }}'
    autostart: '{{ "yes" if (item.autostart|d(true)) else "no" }}'
  with_flattened: '{{ libvirt_networks }}'
  become: false
  when:
    - item.name|d()
    - item.state is undefined or item.state not in [ 'undefined', 'absent' ]
    - item.interface_present is undefined or
      item.interface_present in ansible_interfaces and not item.uri|d()
